### ISSUE TITLE
[Bug]: Generated pyright ignore comments are incorrect

### ISSUE THREAD

**Issue by Popkornium18** [chrisgrieser/nvim-rulebook#1]
### Bug Description

Currently this plugin generates comments like this: `# pyright: ignore reportGeneralTypeIssues`. This turns pyright off completely for this line, because everything after `# pyright: ignore` is ignored. The correct syntax to ignore a set of specific rules is `# pyright: ignore[someRule,someOtherRule]`

### neovim version

```Text
0.9
```

### Make sure you have done the following

- [X] I have updated to the latest version of the plugin.

**Comment by chrisgrieser** [comment]
thx, fixed
