### ISSUE TITLE
FR: Support comments disabling multiple rules

### ISSUE THREAD

**Issue by Popkornium18** [chrisgrieser/nvim-rulebook#2]
### Bug Description

Currently it is not possible to ignore multiple pyright rules, as nvim-rulebook does not support the `# pyright: ignore[ruleA,ruleB,ruleC]` syntax and just chains them like this`# pyright: ignore [ruleA] # pyright: ignore [ruleB] # pyright: ignore [ruleC]`

### To Reproduce

- Introduce statement with multiple errors like `unused = undefined(False)`
- Try to ignore all the errors
- nvim-rulebook keeps chaining ignore comments indefinitely

### neovim version

```Text
0.9
```

### Make sure you have done the following

- [X] I have updated to the latest version of the plugin.

**Comment by chrisgrieser** [comment]
yeah, that's currently not implemented yet.
